## GitHub: 
https://github.com/Twinbo/Computational-Social-Science-2026

## Group Memebers:
Equal group contribution, Haseeb s244701, Malthe s246133 & David s230106

## Part 1: Ready Made vs Custom Made Data

> **Exercise: Ready made data vs Custom made data** In this exercise, I want to make sure you have understood they key points of my lecture and the reading. 
>
> 1. What are pros and cons of the custom-made data used in Centola's experiment (the first study presented in the lecture) and the ready-made data used in Nicolaides's study (the second study presented in the lecture)? You can support your arguments based on the content of the lecture and the information you read in Chapter 2.3 of the book __(answer in max 150 words)__. <br>

<span style="color:red;">
The strength of the Centola’s experiments comes from the custom-made data where the environment is controlled and the network structure is fixed. This makes it easier to identify the behavior patterns of the participants and whether their choices change based on their peers. But a key limitation for this set up is that it is an abstract of the real world, where it doesn’t allow outside factors to influence the peers. 
The strength of the Nicolaides’s study comes from the ready-made data where the data mirrors the real world behavior of the users. This makes it a more precise measurement to see whether the users influence each other. But one big limitation is also the outside factors that can have an huge influence if an user goes out for a run, this could be such as the weather and because it is ready-made data the outside factors is not measurable.
</span> <br>

> 2. How do you think these differences can influence the interpretation of the results in each study? __(answer in max 150 words)__ <br>

<span style="color:red;">
The interpretation of the results in each study is different, because in one study the environment doesn’t change and it is controlled, which doesn’t match the real-world scenarios, because in the real world there could be multiple factors to why people behave as they do when they are in a group. And in the other study it matches more the real-world scenario where it allows the out side factors to have an role in the choices of the people, but these outside factors are not measurable and therefore they are hard to account for. 
</span> <br>

## Part 2: Find Researchers using the OpenAlex API

> **Exercise 3: Find potential Computational Social Scientists** In this exercise, we'll use the OpenAlex API to compile a list of researchers in the field of Computational Social Science, focusing on those who have attended the IC2S2 conference in 2025. This will not only later on help you understand the landscape of Computational Social Science research but also develop practical skills in data collection and analysis. 
>
> Please read the text of the whole exercise before starting to work on it. 
>
> **Steps**
> 
> 1. **Retreive data.** Consider the set of unique researcher names that you collected in Week 1, Exercise 3. Use the _authors_ endpoint of the [OpenAlex API](https://docs.openalex.org/api-entities/authors) to _search_ these researchers in the database based on their names. Loop through the list and, for each researcher in your list, find: 
>     - their _id_: The OpenAlex ID for this author.
>     - their _display\_name_: The name of the author as a single string.
>     - their _works\_api\_url_: A URL that will get you a list of all this author's works.
>     - their _h\_index_ : The h-index for this author.
>     - their _works\_count_: The number of  Works this this author has created.
>     - their _country\_code_: The country code of their last known institution
> 2. **Data Storage** Store this information in a Pandas DataFrame and save it to file.
>
>    
> **Handling Challenges**
> 
> I expect that, while working on the steps above, you will encounter several obstacles. As you complete this exercise, you are expected to:     
>
>    - Identify problems that arise.      
>    - Improve your solutions to address such problems, making reasonable decisions when data is incomplete or ambiguous.       
>

In [14]:
import pandas as pd
import requests
from io import StringIO

In [29]:
#we used this code, to read the raw html to understand how it was formated

Navne = pd.read_csv("Names_list.csv")

BASE = "https://api.openalex.org/authors?"
ENDPOINT = "authors?"
API = "api_key=CIcafSHBHxopqOewXo9hYK"

url = BASE + API

params = {
    "search": Navne,
    "per-page": 200,
    "page": 2
}

data = requests.get(url, params=params).json()
data["results"][0]

{'id': 'https://openalex.org/A5070776067',
 'orcid': None,
 'display_name': 'M. A. Murphy',
 'display_name_alternatives': ['M. A. Murphy',
  'M. A. Murphy (2), S. 0. Schlanger ('],
 'relevance_score': 382.0098,
 'works_count': 1,
 'cited_by_count': 27,
 'summary_stats': {'2yr_mean_citedness': 0.0, 'h_index': 1, 'i10_index': 1},
 'ids': {'openalex': 'https://openalex.org/A5070776067', 'orcid': None},
 'affiliations': [],
 'last_known_institutions': None,
 'topics': [{'id': 'https://openalex.org/T10109',
   'display_name': 'Paleontology and Stratigraphy of Fossils',
   'count': 1,
   'score': 0.986299991607666,
   'subfield': {'id': 'https://openalex.org/subfields/1911',
    'display_name': 'Paleontology'},
   'field': {'id': 'https://openalex.org/fields/19',
    'display_name': 'Earth and Planetary Sciences'},
   'domain': {'id': 'https://openalex.org/domains/3',
    'display_name': 'Physical Sciences'}},
  {'id': 'https://openalex.org/T10399',
   'display_name': 'Hydrocarbon exploration and reservoir analysis',
   'count': 1,
   'score': 0.9722999930381775,
   'subfield': {'id': 'https://openalex.org/subfields/2211',
    'display_name': 'Mechanics of Materials'},
   'field': {'id': 'https://openalex.org/fields/22',
    'display_name': 'Engineering'},
   'domain': {'id': 'https://openalex.org/domains/3',
    'display_name': 'Physical Sciences'}},
  {'id': 'https://openalex.org/T10965',
   'display_name': 'Geological formations and processes',
   'count': 1,
   'score': 0.9995999932289124,
   'subfield': {'id': 'https://openalex.org/subfields/1904',
    'display_name': 'Earth-Surface Processes'},
   'field': {'id': 'https://openalex.org/fields/19',
    'display_name': 'Earth and Planetary Sciences'},
   'domain': {'id': 'https://openalex.org/domains/3',
    'display_name': 'Physical Sciences'}}],
 'topic_share': [{'id': 'https://openalex.org/T10109',
   'display_name': 'Paleontology and Stratigraphy of Fossils',
   'value': 4.5e-06,
   'subfield': {'id': 'https://openalex.org/subfields/1911',
    'display_name': 'Paleontology'},
   'field': {'id': 'https://openalex.org/fields/19',
    'display_name': 'Earth and Planetary Sciences'},
   'domain': {'id': 'https://openalex.org/domains/3',
    'display_name': 'Physical Sciences'}},
  {'id': 'https://openalex.org/T10965',
   'display_name': 'Geological formations and processes',
   'value': 3.8e-06,
   'subfield': {'id': 'https://openalex.org/subfields/1904',
    'display_name': 'Earth-Surface Processes'},
   'field': {'id': 'https://openalex.org/fields/19',
    'display_name': 'Earth and Planetary Sciences'},
   'domain': {'id': 'https://openalex.org/domains/3',
    'display_name': 'Physical Sciences'}},
  {'id': 'https://openalex.org/T10399',
   'display_name': 'Hydrocarbon exploration and reservoir analysis',
   'value': 2.2e-06,
   'subfield': {'id': 'https://openalex.org/subfields/2211',
    'display_name': 'Mechanics of Materials'},
   'field': {'id': 'https://openalex.org/fields/22',
    'display_name': 'Engineering'},
   'domain': {'id': 'https://openalex.org/domains/3',
    'display_name': 'Physical Sciences'}}],
 'x_concepts': [{'id': '127313418',
   'wikidata': 'https://www.wikidata.org/wiki/Q1069',
   'display_name': 'Geology',
   'score': 0.869219183921814},
  {'id': '12294951',
   'wikidata': 'https://www.wikidata.org/wiki/Q44626',
   'display_name': 'Cretaceous',
   'score': 0.8211418986320496},
  {'id': '109007969',
   'wikidata': 'https://www.wikidata.org/wiki/Q749565',
   'display_name': 'Structural basin',
   'score': 0.6855756044387817},
  {'id': '151730666',
   'wikidata': 'https://www.wikidata.org/wiki/Q7205',
   'display_name': 'Paleontology',
   'score': 0.6042958498001099},
  {'id': '17409809',
   'wikidata': 'https://www.wikidata.org/wiki/Q161764',
   'display_name': 'Geochemistry',
   'score': 0.3850650191307068}],
 'counts_by_year': [{'year': 1962,
   'works_count': 1,
   'oa_works_count': 0,
   'cited_by_count': 27}],
 'longest_name': 'M. A. Murphy (2), S. 0. Schlanger (',
 'parsed_longest_name': {'first': 's',
  'middle': '0 schlanger (',
  'last': 'm a murphy',
  'suffix': '',
  'nickname': '2'},
 'block_key': 's m a murphy',
 'works_api_url': 'https://api.openalex.org/works?filter=author.id:A5070776067',
 'updated_date': '2026-02-01T04:19:59.206561',
 'created_date': '2016-06-24'}

In [25]:
BASE = "https://api.openalex.org/authors?"
ENDPOINT = "authors?"
API = "api_key=CIcafSHBHxopqOewXo9hYK"

url = BASE + API

names_series = Navne.iloc[:, 0].astype(str)

rows = []

no_results = 0
errors = 0

for name in names_series:
    params = {
        "search": name,
        "per-page": 200,
        "page": 1
    }

    data = requests.get(url, params=params).json()

    results = data.get("results", [])

    if not results:
        continue

    n = results[0] 
    
    h_index = (n.get("summary_stats") or {}).get("h_index") 
    
    country = (
        n["affiliations"][0]["institution"]["country_code"]
        if n["affiliations"] else None
    )

    rows.append({
        "id": n["id"],
        "display_name": n["display_name"],
        "works_count": n["works_count"],
        "work_api": n["works_api_url"],
        "country_code": country,
        "h_index": h_index
    })

df_d1 = pd.DataFrame(rows).drop_duplicates("id")
df_d1.to_csv("df_d1.csv", index=False)
df_d1

,id,display_name,works_count,work_api,country_code,h_index
0,https://openalex.org/A5002490736,A. K. Tyagi,741,https://api.openalex.org/works?filter=author.i...,IN,68
1,https://openalex.org/A5014647140,Aaron Clauset,267,https://api.openalex.org/works?filter=author.i...,US,47
2,https://openalex.org/A5089395967,Aaron Nichols,10,https://api.openalex.org/works?filter=author.i...,US,3
3,https://openalex.org/A5039995516,Aaron Reeves,254,https://api.openalex.org/works?filter=author.i...,GB,48
4,https://openalex.org/A5021334672,Joshua Maynez,51,https://api.openalex.org/works?filter=author.i...,US,12
...,...,...,...,...,...,...
1080,https://openalex.org/A5032277739,Pavel Dimitrov Chachev,2,https://api.openalex.org/works?filter=author.i...,DE,1
1081,https://openalex.org/A5032431129,Pedro Ramaciotti Morales,79,https://api.openalex.org/works?filter=author.i...,FR,9
1082,https://openalex.org/A5044421492,Peidong Mei,9,https://api.openalex.org/works?filter=author.i...,GB,2
1083,https://openalex.org/A5021833788,Peng Liu,572,https://api.openalex.org/works?filter=author.i...,CN,84
1084,https://openalex.org/A5048966126,Peter Selb,93,https://api.openalex.org/works?filter=author.i...,DE,20

<span style="color:red;">
We did alot of request on the day this was ran, so its missing some authors. The first time we ran it, we got around 1500 author ids, for D1 dataset.
</span> <br>

###  **Reflection Questions**
>  Answer the following questions __(max 150 words for each question)__: 
>
>    - Which challenges did you encounter? How did you address them?


<span style="color:red;">
it was our first time using a open API to retrive data, which specific requirements, so we need to dig in to OpenAlex extensive documentation about the api and paramerters. <br>
</span> <br>

>    - Choose one problem you faced while collecting the data and describe your solution. Why did you choose this approach, and what impact might it have on your data? 

<span style="color:red;">
We did not know how the API data request was formated, so we looked in to the raw HTML data, and read how each required information about the author was stored. We found out there were a lot of dicts with different information, so we needed to exctract only the wanted details in the "results" call. 
</span> <br>

## Part 3: Collect Research Articles

> **Exercise 1: Collecting Research Articles from IC2S2 Authors**
>
>In this exercise, we'll leverage the OpenAlex API to gather information on research articles authored by participants of the IC2S2 2025 conference, referred to as *IC2S2 authors*. **Before you start, please ensure you read through the entire exercise.**
>
> 
> **Steps:**
>  
> 1. **Retrieve Data:** Start with the dataset of *IC2S2 authors* you collected in Week 2, Exercise 3 (called dataset D1 in the figure above). Use the OpenAlex API [works endpoint](https://docs.openalex.org/api-entities/works) to fetch their research articles. For each article, retrieve the following details:
>    - _id_: The unique OpenAlex ID for the work.
>    - _publication_year_: The year the work was published.
>    - _cited_by_count_: The number of times the work has been cited by other works.
>    - _author_ids_: The OpenAlex IDs for the authors of the work.
>    - _title_: The title of the work.
>    - _abstract_inverted_index_: The abstract of the work, formatted as an inverted index.
> 
>     **Important Note on Paging:** By default, the OpenAlex API limits responses to 25 works per request. For more efficient data retrieval, I suggest to adjust this limit to 200 works per request. Even with this adjustment, you will need to implement pagination to access all available works for a given query. This ensures you can systematically retrieve the complete set of works beyond the initial 200. Find guidance on implementing pagination [here](https://docs.openalex.org/how-to-use-the-api/get-lists-of-entities/paging#cursor-paging).
>
> 2. **Data Storage:** Organize the retrieved information into two Pandas DataFrames and save them to two files in a suitable format:
>    - Dataset D2: The *IC2S2 papers* dataset should include: *id, publication\_year, cited\_by\_count, author\_ids*.
>    - Dataset D3: The *IC2S2 abstracts* dataset should include: *id, title, abstract\_inverted\_index*.
>  
>
> **Filters:**
> To ensure the data we collect is relevant and manageable, apply the following filters:
>     
>    - Only include *IC2S2 authors* with a total work count between 5 and 5,000.    
>    - Retrieve only works that have received more than 10 citations.    
>    - Limit to works authored by fewer than 10 individuals.    
>    - Include only works relevant to Computational Social Science (focusing on: Sociology OR Psychology OR Economics OR Political Science) AND intersecting with a quantitative discipline (Mathematics OR Physics OR Computer Science), as defined by their [Concepts](https://docs.openalex.org/api-entities/works/work-object#concepts). *Note*: here we only consider Concepts at *level=0* (the most coarse definition of concepts).     
>
> **Efficiency Tips:**
> Writing efficient code in this exercise is **crucial**. To speed up your process:
> 
> - **Apply filters directly in your request:** When possible, use the [filter parameter](https://docs.openalex.org/api-entities/works/filter-works) of the *works* endpoint to apply the filters above directly in your API request, ensuring only relevant data is returned. Learn about combining multiple filters [here](https://docs.openalex.org/how-to-use-the-api/get-lists-of-entities/filter-entity-lists).  
> - **Bulk requests:** Instead of sending one request for each author, you can use the [filter parameter](https://docs.openalex.org/api-entities/works/filter-works) to query works by multiple authors in a single request. *Note: My testing suggests that can only include up to 25 authors per request.*
> - **Use multiprocessing:** Implement multiprocessing to handle multiple requests simultaneously. I highly recommmend [Joblib’s Parallel](https://joblib.readthedocs.io/en/stable/) function for that, and [tqdm](https://tqdm.github.io/) can help monitor progress of your jobs. Remember to stay within [the rate limit](https://docs.openalex.org/how-to-use-the-api/rate-limits-and-authentication) of 100 requests per second.
>
>
>   
> For reference, employing these strategies allowed me to fetch the data in about 30 seconds using 5 cores on my laptop. I obtained a dataset of approximately 25 MB (including both the *IC2S2 abstracts* and *IC2S2 papers* files).

<span style="color:red;">
To understand how consept id worked, we need to again to into the HTML and read the formatting, where we found each concept had its one id for example Computer science was C41008148. We compiled a list of the relevant id and used it in our api request.
</span> <br>

In [30]:
url = "https://api.openalex.org/concepts?filter=level:0"
data = requests.get(url).json()
data["results"][0]

{'id': 'https://openalex.org/C41008148',
 'wikidata': 'https://www.wikidata.org/wiki/Q21198',
 'display_name': 'Computer science',
 'level': 0,
 'description': 'theoretical study of the formal foundation enabling the automated processing or computation of information, for example on a computer or over a data transmission network',
 'works_count': 165039134,
 'cited_by_count': 752144837,
 'summary_stats': None,
 'ids': {'openalex': 'https://openalex.org/C41008148',
  'wikidata': 'https://www.wikidata.org/wiki/Q21198',
  'mag': None,
  'wikipedia': 'https://en.wikipedia.org/wiki/computer_science',
  'umls_aui': None,
  'umls_cui': None},
 'image_url': 'https://upload.wikimedia.org/wikipedia/commons/6/6a/Sorting_quicksort_anim.gif',
 'image_thumbnail_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Sorting_quicksort_anim.gif/100px-Sorting_quicksort_anim.gif',
 'international': {},
 'ancestors': None,
 'related_concepts': None,
 'counts_by_year': None,
 'works_api_url': 'https://api.openalex.org/works?filter=concepts.id:41008148',
 'updated_date': '2026-02-27T04:03:05',
 'created_date': '2016-06-24T00:00:00'}

<span style="color:red;">
After understanding how concepts id worked, implemented the rest of the code using pagination to request the next page if the results gave more than 200 works, to insure all data was retrieved. We chose to up the efficiency by getting dataset 2 and 3, at the same time as there shared some parameters, and just split it after. Which can be seen below.
</span> <br>

In [10]:
df_d1 = pd.read_csv("../Week 2/df_d1.csv")

df_d1 = df_d1[(df_d1["works_count"] >= 5) & (df_d1["works_count"] <= 5000)]
df_d1

,id,display_name,works_count,work_api,country_code
0,https://openalex.org/A5002490736,A. K. Tyagi,741,https://api.openalex.org/works?filter=author.i...,IN
1,https://openalex.org/A5014647140,Aaron Clauset,267,https://api.openalex.org/works?filter=author.i...,US
2,https://openalex.org/A5089395967,Aaron Nichols,10,https://api.openalex.org/works?filter=author.i...,US
3,https://openalex.org/A5039995516,Aaron Reeves,254,https://api.openalex.org/works?filter=author.i...,GB
4,https://openalex.org/A5021334672,Joshua Maynez,50,https://api.openalex.org/works?filter=author.i...,US
...,...,...,...,...,...
1490,https://openalex.org/A5004566032,Emőke-Ágnes Horvát,72,https://api.openalex.org/works?filter=author.i...,US
1491,https://openalex.org/A5054348632,Ákos Huszár,35,https://api.openalex.org/works?filter=author.i...,HU
1492,https://openalex.org/A5079294298,Émilien Schultz,114,https://api.openalex.org/works?filter=author.i...,FR
1493,https://openalex.org/A5022704573,Étienne Ollion,131,https://api.openalex.org/works?filter=author.i...,FR
1496,https://openalex.org/A5093136191,Şükrü Atsızelti,8,https://api.openalex.org/works?filter=author.i...,TR

In [27]:
rows_d2_3 = []

api = "CIcafSHBHxopqOewXo9hYK"

for name in df_d1["work_api"]:
    
    page = 1
    
    
    while True:
    
        url = (
        f"{name},authors_count:<10,cited_by_count:>10,"
        "concepts.id:C144024400|C15744967|C162324750|C17744445,"
        "concepts.id:C33923547|C121332964|C41008148"
        f"&per-page=200&page={page}"
        "&select=id,publication_year,cited_by_count,title,abstract_inverted_index,authorships"
        f"&api_key={api}"        )

        data = requests.get(url).json()
        results = data.get("results", [])

        if not results:
            break

        for work in results:
            corresponding_ids = []
            for authorship in work["authorships"]:
                    corresponding_ids.append(authorship["author"]["id"])
            
            rows_d2_3.append({
                "work_id": work["id"],
                "title": work["title"],
                "publication_year": work["publication_year"],
                "cited_by_count": work["cited_by_count"],
                "author_ids": corresponding_ids,
                "abstract_inverted_index": work["abstract_inverted_index"]
            })
            
        if len(results) < 200:
            break
            
        page += 1  

df2_3 = pd.DataFrame(rows_d2_3).drop_duplicates("work_id")
df2_3

,work_id,title,publication_year,cited_by_count,author_ids,abstract_inverted_index
0,https://openalex.org/W2398055269,Revealing structural distortion and dielectric...,2016.0,14,"[https://openalex.org/A5055740398, https://ope...",None
1,https://openalex.org/W2047940964,Finding community structure in very large netw...,2004.0,7328,"[https://openalex.org/A5014647140, https://ope...","{'The': [0, 158], 'discovery': [1], 'and': [2,..."
2,https://openalex.org/W3103362336,Power-law distributions in empirical data,2018.0,6724,"[https://openalex.org/A5014647140, https://ope...","{'Power-law': [0], 'distributions': [1, 64], '..."
3,https://openalex.org/W2157082398,Hierarchical structure and the prediction of m...,2008.0,2163,"[https://openalex.org/A5014647140, https://ope...",None
4,https://openalex.org/W2061099285,Performance of modularity maximization in prac...,2010.0,950,"[https://openalex.org/A5069948947, https://ope...","{'Although': [0], 'widely': [1], 'used': [2], ..."
...,...,...,...,...,...,...
12928,https://openalex.org/W2060199383,National Elections in Switzerland: an Introduc...,2006.0,18,"[https://openalex.org/A5026367805, https://ope...","{'“It': [0], 'is': [1], 'difficult': [2], 'to'..."
12929,https://openalex.org/W3033099695,Can we directly survey adherence to non-pharma...,2020.0,17,"[https://openalex.org/A5000465232, https://ope...","{'Self-reports': [0], 'of': [1, 65, 94, 127], ..."
12930,https://openalex.org/W2106259901,Multi-Level Elections in Switzerland,2006.0,20,[https://openalex.org/A5048966126],"{'Why': [0], 'do': [1], 'election': [2, 51, 11..."
12931,https://openalex.org/W4239852643,Tracking and Promoting the Usage of a COVID-19...,2020.0,11,"[https://openalex.org/A5000465232, https://ope...","{'Digital': [0], 'contact': [1, 54, 122], 'tra..."
12932,https://openalex.org/W2297641318,Measuring Political Knowledge in Web-Based Sur...,2015.0,21,"[https://openalex.org/A5000465232, https://ope...","{'Does': [0], 'the': [1, 29, 41, 44, 53, 60, 8..."

In [ ]:
df_2 = df2_3[[
    "work_id",
    "publication_year",
    "cited_by_count",
    "author_ids"
]].copy()

df_2.to_csv("D_2.csv", index=False)

df_3 = df2_3[[
    "work_id",
    "title",
    "author_ids"
]].copy()

df_3.to_csv("D_3.csv", index=False)

>
> **Data Overview and Reflection questions:** Answer the following questions __(max 150 words for each question)__: 
> 
> - **Dataset summary.** How many works are listed in your Dataset D2 (*IC2S2 papers*) dataframe? How many unique researchers have co-authored these works?

<span style="color:red;">
There are X many work in Dataset D2, and there are X unique authors. <br>
</span> <br>

> - **Efficiency in code.** Describe the strategies you implemented to make your code more efficient. How did your approach affect your code's execution time? <br>

<span style="color:red;">
We implementet two different main strategies, first we use paging which is not directly a effiency strategy, but ensured that we got the entire data for each author, so a time saver later on. The second thing we did was apply the filters directly in the URL to effiently retrive the information we needed, saving as time by not having to search through huge requests, with data we did not need.<br>
</span> <br>

> - **Filtering Criteria and Dataset Relevance** Reflect on the rationale behind setting specific thresholds for the total number of works by an author, the citation count, the number of authors per work, and the relevance of works to specific fields. How do these filtering criteria contribute to the relevance of the dataset you compiled? Do you believe any aspects of Computational Social Science research might be underrepresented or overrepresented as a result of these choices?

<span style="color:red;">
We think the total work range for each author, which was set to 5-5000 has some advantages and disadvantages. First of all to cap the max to 5000 excludes some researchers that have alot of experiance in the field, but for data scraping purposes, it is understanderable to have this limit. The minimum limit also exlcudes new authors which only have a couple of works, so there is a chance that their new perspective on something gets underrepresented. Another thing is that its not likely that every author has all of their work uploaded to OpenAlex, if just some important ones with alot of cites exist they also get exlcuded. <br>

By implementing the works that recived 10 or more citations ensures us that we only recieve the work that people in the computationial field deems as being relevent, even though some works with under 10 citations still might be relevent, but this is also a way to ensure the data set not will be to large and filled with irrelevent content.

The limit of works that has ben authored by fewer thatn 10 inndividuals is mainly a computetional limit so the data set will be a bit faster to gather and still keeps it managebel.

The last filter is very imoporten, because this ensures us that we only get the relevent work that focusses on fields in Computational Social Science.

Overall we think that the filteres ensure a diverse span of works in the Computational Social Science, while focusing on the main research area, even if some edge cases get excluded.


</span> <br>